### ISSUE TITLE
No Idea the motivation of this project

### ISSUE THREAD

**Issue by GeorgeS2019** [LittleLittleCloud/dotnet-interactive-agent#1]

**Comment by LittleLittleCloud** [comment]
The motivation is use dotnet-interactive as code interpreter for multi-language support
- C#
- pwsh
- python

 Maybe the following issue would give more context

- https://github.com/microsoft/autogen/issues/3316

**Comment by LittleLittleCloud** [comment]
@GeorgeS2019 I just update the readme, the motivation of this project is more clear now.
